### ISSUE TITLE
Erreur des tests

### ISSUE THREAD

**Issue by lynchmaniac** [wmoulin/threerest#3]
Les tests échouent actuellement car ServiceHal.testHal n'est pas une fonction.
Je peux pas déboguer d'où je suis mais si cela peut attendre je regarde cela ce midi normalement.

**Comment by wmoulin** [comment]
Moi ça fonctionnait, je regarde de mon côté.

**Comment by wmoulin** [comment]
Je confirme, c'est OK. Tu ne dois pas être à jour.

**Comment by lynchmaniac** [comment]
Pourtant si je suis à jour de ce matin. Bon je check ce midi, cela doit être un souci d'interface chaise clavier. je te tiens au jus.
